package model;

// Generated Jan 2, 2014 6:19:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AffecterId generated by hbm2java
 */
@Embeddable
public class AffecterId implements java.io.Serializable {

	private int matricule;
	private int idPoste;
	private int date;

	public AffecterId() {
	}

	public AffecterId(int matricule, int idPoste, int date) {
		this.matricule = matricule;
		this.idPoste = idPoste;
		this.date = date;
	}

	@Column(name = "matricule", nullable = false)
	public int getMatricule() {
		return this.matricule;
	}

	public void setMatricule(int matricule) {
		this.matricule = matricule;
	}

	@Column(name = "id_poste", nullable = false)
	public int getIdPoste() {
		return this.idPoste;
	}

	public void setIdPoste(int idPoste) {
		this.idPoste = idPoste;
	}

	@Column(name = "date", nullable = false)
	public int getDate() {
		return this.date;
	}

	public void setDate(int date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AffecterId))
			return false;
		AffecterId castOther = (AffecterId) other;

		return (this.getMatricule() == castOther.getMatricule())
				&& (this.getIdPoste() == castOther.getIdPoste())
				&& (this.getDate() == castOther.getDate());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMatricule();
		result = 37 * result + this.getIdPoste();
		result = 37 * result + this.getDate();
		return result;
	}

}
