package model;

// Generated Jan 1, 2014 9:04:01 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AvoirId generated by hbm2java
 */
@Embeddable
public class AvoirId implements java.io.Serializable {

	private int idEcole;
	private int matricule;
	private int idDiplome;

	public AvoirId() {
	}

	public AvoirId(int idEcole, int matricule, int idDiplome) {
		this.idEcole = idEcole;
		this.matricule = matricule;
		this.idDiplome = idDiplome;
	}

	@Column(name = "id_ecole", nullable = false)
	public int getIdEcole() {
		return this.idEcole;
	}

	public void setIdEcole(int idEcole) {
		this.idEcole = idEcole;
	}

	@Column(name = "matricule", nullable = false)
	public int getMatricule() {
		return this.matricule;
	}

	public void setMatricule(int matricule) {
		this.matricule = matricule;
	}

	@Column(name = "id_diplome", nullable = false)
	public int getIdDiplome() {
		return this.idDiplome;
	}

	public void setIdDiplome(int idDiplome) {
		this.idDiplome = idDiplome;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AvoirId))
			return false;
		AvoirId castOther = (AvoirId) other;

		return (this.getIdEcole() == castOther.getIdEcole())
				&& (this.getMatricule() == castOther.getMatricule())
				&& (this.getIdDiplome() == castOther.getIdDiplome());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEcole();
		result = 37 * result + this.getMatricule();
		result = 37 * result + this.getIdDiplome();
		return result;
	}

}
