package model;

// Generated 29 d�c. 2013 02:33:39 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Competence generated by hbm2java
 */
@Entity
@Table(name = "competence", catalog = "bddsqli")
public class Competence implements java.io.Serializable {

	private Integer idCompetence;
	private Technolgie technolgie;
	private String libelleCompetence;
	private Set<Metriser> metrisers = new HashSet<Metriser>(0);

	public Competence() {
	}

	public Competence(Technolgie technolgie, String libelleCompetence) {
		this.technolgie = technolgie;
		this.libelleCompetence = libelleCompetence;
	}

	public Competence(Technolgie technolgie, String libelleCompetence,
			Set<Metriser> metrisers) {
		this.technolgie = technolgie;
		this.libelleCompetence = libelleCompetence;
		this.metrisers = metrisers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_competence", unique = true, nullable = false)
	public Integer getIdCompetence() {
		return this.idCompetence;
	}

	public void setIdCompetence(Integer idCompetence) {
		this.idCompetence = idCompetence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_technologie", nullable = false)
	public Technolgie getTechnolgie() {
		return this.technolgie;
	}

	public void setTechnolgie(Technolgie technolgie) {
		this.technolgie = technolgie;
	}

	@Column(name = "libelle_competence", nullable = false)
	public String getLibelleCompetence() {
		return this.libelleCompetence;
	}

	public void setLibelleCompetence(String libelleCompetence) {
		this.libelleCompetence = libelleCompetence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competence")
	public Set<Metriser> getMetrisers() {
		return this.metrisers;
	}

	public void setMetrisers(Set<Metriser> metrisers) {
		this.metrisers = metrisers;
	}

}
