package model;

// Generated Jan 1, 2014 9:04:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Diplome generated by hbm2java
 */
@Entity
@Table(name = "diplome", catalog = "bddsqli")
public class Diplome implements java.io.Serializable {

	private Integer idDiplome;
	private String niveau;
	private String typeDiplome;
	private Set<Avoir> avoirs = new HashSet<Avoir>(0);

	public Diplome() {
	}

	public Diplome(String niveau, String typeDiplome) {
		this.niveau = niveau;
		this.typeDiplome = typeDiplome;
	}

	public Diplome(String niveau, String typeDiplome, Set<Avoir> avoirs) {
		this.niveau = niveau;
		this.typeDiplome = typeDiplome;
		this.avoirs = avoirs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_diplome", unique = true, nullable = false)
	public Integer getIdDiplome() {
		return this.idDiplome;
	}

	public void setIdDiplome(Integer idDiplome) {
		this.idDiplome = idDiplome;
	}

	@Column(name = "niveau", nullable = false, length = 50)
	public String getNiveau() {
		return this.niveau;
	}

	public void setNiveau(String niveau) {
		this.niveau = niveau;
	}

	@Column(name = "type_diplome", nullable = false, length = 50)
	public String getTypeDiplome() {
		return this.typeDiplome;
	}

	public void setTypeDiplome(String typeDiplome) {
		this.typeDiplome = typeDiplome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "diplome")
	public Set<Avoir> getAvoirs() {
		return this.avoirs;
	}

	public void setAvoirs(Set<Avoir> avoirs) {
		this.avoirs = avoirs;
	}

}
