package model;

// Generated Jan 2, 2014 6:19:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ecole generated by hbm2java
 */
@Entity
@Table(name = "ecole", catalog = "bddsqli")
public class Ecole implements java.io.Serializable {

	private Integer idEcole;
	private String nomEcole;
	private String typeEcole;
	private Set<Avoir> avoirs = new HashSet<Avoir>(0);

	public Ecole() {
	}

	public Ecole(String nomEcole, String typeEcole) {
		this.nomEcole = nomEcole;
		this.typeEcole = typeEcole;
	}

	public Ecole(String nomEcole, String typeEcole, Set<Avoir> avoirs) {
		this.nomEcole = nomEcole;
		this.typeEcole = typeEcole;
		this.avoirs = avoirs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_ecole", unique = true, nullable = false)
	public Integer getIdEcole() {
		return this.idEcole;
	}

	public void setIdEcole(Integer idEcole) {
		this.idEcole = idEcole;
	}

	@Column(name = "nom_ecole", nullable = false)
	public String getNomEcole() {
		return this.nomEcole;
	}

	public void setNomEcole(String nomEcole) {
		this.nomEcole = nomEcole;
	}

	@Column(name = "type_ecole", nullable = false)
	public String getTypeEcole() {
		return this.typeEcole;
	}

	public void setTypeEcole(String typeEcole) {
		this.typeEcole = typeEcole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecole")
	public Set<Avoir> getAvoirs() {
		return this.avoirs;
	}

	public void setAvoirs(Set<Avoir> avoirs) {
		this.avoirs = avoirs;
	}

}
