package model;

// Generated Jan 2, 2014 6:19:27 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Metriser generated by hbm2java
 */
@Entity
@Table(name = "metriser", catalog = "bddsqli")
public class Metriser implements java.io.Serializable {

	private MetriserId id;
	private Competence competence;
	private Collaborateur collaborateur;
	private int niveauExpertise;

	public Metriser() {
	}

	public Metriser(MetriserId id, Competence competence,
			Collaborateur collaborateur, int niveauExpertise) {
		this.id = id;
		this.competence = competence;
		this.collaborateur = collaborateur;
		this.niveauExpertise = niveauExpertise;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "matricule", column = @Column(name = "matricule", nullable = false)),
			@AttributeOverride(name = "idCompetence", column = @Column(name = "id_competence", nullable = false)) })
	public MetriserId getId() {
		return this.id;
	}

	public void setId(MetriserId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_competence", nullable = false, insertable = false, updatable = false)
	public Competence getCompetence() {
		return this.competence;
	}

	public void setCompetence(Competence competence) {
		this.competence = competence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matricule", nullable = false, insertable = false, updatable = false)
	public Collaborateur getCollaborateur() {
		return this.collaborateur;
	}

	public void setCollaborateur(Collaborateur collaborateur) {
		this.collaborateur = collaborateur;
	}

	@Column(name = "niveau_expertise", nullable = false)
	public int getNiveauExpertise() {
		return this.niveauExpertise;
	}

	public void setNiveauExpertise(int niveauExpertise) {
		this.niveauExpertise = niveauExpertise;
	}

}
