package model;

// Generated Jan 2, 2014 6:19:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MetriserId generated by hbm2java
 */
@Embeddable
public class MetriserId implements java.io.Serializable {

	private int matricule;
	private int idCompetence;

	public MetriserId() {
	}

	public MetriserId(int matricule, int idCompetence) {
		this.matricule = matricule;
		this.idCompetence = idCompetence;
	}

	@Column(name = "matricule", nullable = false)
	public int getMatricule() {
		return this.matricule;
	}

	public void setMatricule(int matricule) {
		this.matricule = matricule;
	}

	@Column(name = "id_competence", nullable = false)
	public int getIdCompetence() {
		return this.idCompetence;
	}

	public void setIdCompetence(int idCompetence) {
		this.idCompetence = idCompetence;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MetriserId))
			return false;
		MetriserId castOther = (MetriserId) other;

		return (this.getMatricule() == castOther.getMatricule())
				&& (this.getIdCompetence() == castOther.getIdCompetence());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMatricule();
		result = 37 * result + this.getIdCompetence();
		return result;
	}

}
